# Generated by Django 4.2 on 2023-07-01 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography_album', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographs',
            name='upload_date',
            field=models.DateField(auto_now=True),
        ),
    ]
