# Generated by Django 4.2 on 2023-07-01 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photography_album', '0002_photographs_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographs',
            name='uploaded_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
