# Generated by Django 4.2 on 2023-07-01 20:53

from django.db import migrations, models
import main.validator


class Migration(migrations.Migration):

    dependencies = [
        ('photography_album', '0008_alter_photographs_photograph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographs',
            name='photograph',
            field=models.ImageField(default='avatar.jpg', upload_to='photographs', validators=[main.validator.validate_image]),
        ),
    ]
