# Generated by Django 4.2 on 2023-07-16 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photography_album', '0010_photographs_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographs',
            name='uploaded_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('album_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Untitled', max_length=100)),
                ('description', models.CharField(max_length=500, null=True)),
                ('created_date', models.DateField(auto_now=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Albums',
                'verbose_name_plural': 'Ablums',
            },
        ),
    ]
