# Generated by Django 4.2 on 2023-07-17 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photography_album', '0011_alter_photographs_uploaded_by_albums'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumContents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_id', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='photography_album.albums')),
                ('photograph_id', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='photography_album.photographs')),
            ],
            options={
                'verbose_name': 'Album Contents',
                'verbose_name_plural': 'Album Contents',
            },
        ),
    ]
