# Generated by Django 4.2 on 2023-07-17 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photography_album', '0012_albumcontents'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='albums',
            options={'verbose_name': 'Albums', 'verbose_name_plural': 'Albums'},
        ),
        migrations.AddField(
            model_name='albumcontents',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='albumcontents',
            name='album_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='photography_album.albums'),
        ),
        migrations.AlterField(
            model_name='albumcontents',
            name='photograph_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='photography_album.photographs'),
        ),
    ]
