# Generated by Django 4.2 on 2023-07-17 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photography_album', '0013_alter_albums_options_albumcontents_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumcontents',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
